# 自定义异常

使用Java内置的异常类可以描述在编程时出现的大部分异常情况。除此之外，用户还可以自定义异常。

用户自定义异常类，只需继承 `Exception` 类即可。

在程序中使用自定义异常类，大体可分为以下几个步骤:

创建自定义异常类。

在方法中通过 `throw` 关键字抛出异常对象。

如果在当前抛出异常的方法中处理异常，可以使用 `try-catch` 语句捕获并处理；否则在方法的

声明处通过 `throws` 关键字指明要抛出给方法调用者的异常，继续进行下一步操作。

在出现异常方法的调用者中捕获并处理异常。

```java
class MyException extends Exception { 

private int detail; 

MyException(int a){ 

detail = a; 

}

public String toString(){ 

return "MyException ["+ detail + "]"; 

} 

}

public class TestMyException{ 

static void compute(int a) throws MyException{ 

System.out.println("Called compute(" + a + ")"); 

if(a > 10){ 

throw new MyException(a); 

}

System.out.println("Normal exit!"); 

}

public static void main(String [] args){

try{

compute(1); 

compute(20); 

}catch(MyException me){ 

System.out.println("Caught " + me); 

} 

} 

} 
```

【结果】

```java
Called compute(1) 

Normal exit! 

Called compute(20) 

Caught MyException [20] 
```

